name: Android APK Extractor

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  apk:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: gradle

    # - name: Build debug APK
    #   run: bash ./gradlew assembleDebug --stacktrace
    
    - name : Grant execute permission for gradlew
      run : chmod +x gradlew
    
    - name : Build with Gradle
      run : ./gradlew build
      
    - name: Build Release
      id : buildRelease
      run : ./gradlew bundleRelease
      
    - name: Sign Android Releases
      uses: jonfazzaro/sign-android-release@v1.0.1
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASS }}
        keyPassword: ${{ secrets.KEY_PASS }}  
      
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: apk
        path: app/build/outputs/apk/release/Messenger_signed.apk
     
