name: Android APK Extractor

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  apk:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: gradle

    # - name: Build debug APK
    #   run: bash ./gradlew assembleDebug --stacktrace
    
    - name : Grant execute permission for gradlew
      run : chmod +x gradlew
    
    - name : Build with Gradle
      run : ./gradlew build
      
    - name: Build Release
      id : buildRelease
      run : ./gradlew bundleRelease
      
    - name: Sign Android Releases
    # You may pin to the exact commit or the version.
    # uses: jonfazzaro/sign-android-release@aff7002d926880ee0f362787cc9be15fc5a1c462
      uses: jonfazzaro/sign-android-release@v1.0.1
      with:
        # The directory to find your release to sign
        releaseDirectory: app/build/outputs/apk/release
        # The key used to sign your release in base64 encoded format
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        # The key alias
        alias: ${{ secrets.ALIAS }}
        # The password to the keystore
        keyStorePassword: clamos11#$
        #keyStorePassword: ${{ secrets.KEY_STORE_PASS }}
        # The password for the key
        keyPassword: ${{ secrets.KEY_PASS }}  
      
    #- name: Upload APK
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: app.apk
    #    path: app/build/outputs/apk/debug
     
